### ISSUE TITLE
Module not found: ApiClient

### ISSUE THREAD

**Issue by malishahi** [Waziup/wazicloud-js#3]
I tried to use wazuip-js in reactjs dashboard, but I faced the following error. I followd the instruction on how to use for development in README.

../waziup-js/src/index.js
Module not found: Can't resolve 'ApiClient' in '/home/mehdi/git/waziup-js/src'

**Comment by malishahi** [comment]
@selombanybah I will be waiting for your help.

**Comment by cdupont** [comment]
Solved. It should be working now.
